//! Build-time isolation crate for the Slint UI.
//!
//! `slint::include_modules!()` pulls in the generated UI module (~345k lines
//! for the full tree) — keeping it here means the root crate's Rust edits
//! don't pay for recompiling it. Everything the generated code exports
//! (components, structs from ui/tokens.slint, globals) lands at this crate's
//! root; the app imports it with `use dm_ui::*;`.

slint::include_modules!();

/// Auto-generated by build.rs — exposes `EMOJI_POSITIONS` and `TILE`.
pub mod emoji_sprite_map {
    include!(concat!(env!("OUT_DIR"), "/emoji_sprite_map.rs"));
}

/// The composed Twemoji sprite PNG, embedded as bytes by build.rs.
pub const EMOJI_SPRITE_PNG: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/twemoji_sprite.png"));
